-- ============================================================================
-- Project Cloud BI Platform
-- ML prescriptive budget scenarios
-- ============================================================================

CREATE OR REPLACE VIEW `{project_id}.{ml_dataset}.budget_scenarios` AS
SELECT
  scenario_id,
  scenario_name,
  scenario_type,
  allocation_method,
  budget_multiplier,
  scholarship_multiplier,
  poverty_weight,
  demand_weight,
  population_weight,
  coverage_weight,
  first_generation_weight,
  balanced_priority_weight,
  scenario_description,
  scenario_version,
  CURRENT_TIMESTAMP() AS created_at
FROM UNNEST([
  STRUCT(
    'base_priority' AS scenario_id,
    'Base score v2' AS scenario_name,
    'base' AS scenario_type,
    'priority_score_v2' AS allocation_method,
    1.00 AS budget_multiplier,
    1.00 AS scholarship_multiplier,
    0.00 AS poverty_weight,
    0.00 AS demand_weight,
    0.00 AS population_weight,
    0.00 AS coverage_weight,
    0.00 AS first_generation_weight,
    1.00 AS balanced_priority_weight,
    'Escenario base que distribuye presupuesto segun el score regional v2 balanceado.' AS scenario_description,
    'regional_allocation_scenarios_v1' AS scenario_version
  ),
  STRUCT(
    'budget_plus_10',
    'Presupuesto +10%',
    'budget_increase',
    'priority_score_v2',
    1.10,
    1.10,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    1.00,
    'Escenario que mantiene el ranking por score v2 y simula un incremento presupuestal de 10%.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'budget_plus_20',
    'Presupuesto +20%',
    'budget_increase',
    'priority_score_v2',
    1.20,
    1.20,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    1.00,
    'Escenario que mantiene el ranking por score v2 y simula un incremento presupuestal de 20%.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'budget_minus_10',
    'Presupuesto -10%',
    'budget_decrease',
    'priority_score_v2',
    0.90,
    0.90,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    1.00,
    'Escenario que mantiene el ranking por score v2 y simula una reduccion presupuestal de 10%.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'poverty_focus',
    'Enfoque pobreza',
    'equity',
    'poverty_weighted',
    1.00,
    1.00,
    0.60,
    0.15,
    0.10,
    0.05,
    0.10,
    0.00,
    'Escenario de equidad que prioriza pobreza y mantiene demanda, poblacion joven, primera generacion y cobertura como senales complementarias.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'demand_population_focus',
    'Enfoque demanda y poblacion joven',
    'demand',
    'demand_population_weighted',
    1.00,
    1.00,
    0.10,
    0.45,
    0.35,
    0.05,
    0.05,
    0.00,
    'Escenario que prioriza demanda educativa y poblacion joven con senales sociales complementarias.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'first_generation_focus',
    'Enfoque primera generacion',
    'social_mobility',
    'first_generation_weighted',
    1.00,
    1.00,
    0.25,
    0.15,
    0.05,
    0.05,
    0.50,
    0.00,
    'Escenario de movilidad social que prioriza primera generacion universitaria con pobreza y demanda como soporte.',
    'regional_allocation_scenarios_v1'
  ),
  STRUCT(
    'balanced_equity_demand',
    'Balance equidad-demanda',
    'balanced',
    'multi_factor_weighted',
    1.00,
    1.00,
    0.30,
    0.25,
    0.15,
    0.15,
    0.15,
    0.00,
    'Escenario balanceado de equidad territorial y demanda educativa con cobertura en peso no dominante.',
    'regional_allocation_scenarios_v1'
  )
]);
